services:
  duck_transcriber:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: duck_transcriber
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:/app/data/duck_transcriber.db
      - WHISPER_LOCAL_URL=http://host.docker.internal:8080/inference
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
