services:
  duck_transcriber:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: duck_transcriber
    restart: unless-stopped
    environment:
      - WHISPER_LOCAL_URL=http://host.docker.internal:8080/inference
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
