name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install dependencies
              run: sudo apt-get install -y libssl-dev pkg-config
            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@stable
            - name: Install Zig toolchain
              uses: korandoru/setup-zig@v1
              with:
                zig-version: 0.10.0
            - name: Install Cargo Lambda
              uses: jaxxstorm/action-install-gh-release@v1.9.0
              with:
                repo: cargo-lambda/cargo-lambda
                platform: linux # Other valid options: 'windows' or 'darwin'
                arch: aarch64 # Other valid options for linux: 'aarch64'
            - name: Check if code compiles
              run: cargo lambda build --arm64 # no release for faster builds (this isn't going into prod)